# Generated by Django 5.2.8 on 2026-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=50)),
                ('permission', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('role', 'product_id', 'feature', 'permission')},
            },
        ),
    ]
